export const Images = {
  logo: "/assets/img/icon/logo.svg",
  dashboard: "/assets/img/icon/dashboard.svg",
  product: "/assets/img/icon/product.svg",
  customers: "/assets/img/icon/customer.svg",
  income: "/assets/img/icon/income.svg",
  promote: "/assets/img/icon/promote.svg",
  help: "/assets/img/icon/help.svg",
  right_arrow: "/assets/img/icon/right_arrow.svg",
  down_arrow: "/assets/img/icon/down_arrow.svg",
  profile: "/assets/img/profile.png",
  search: "/assets/img/icon/search_icon.svg",
  cusomers_logo: "/assets/img/customers_logo.png",
  members_logo: "/assets/img/members_logo.png",
  active_logo: "/assets/img/active_logo.png",
  arrow_up: "assets/img/icon/arrow-up.svg",
  arrow_down: "assets/img/icon/arrow_down.svg",
  right_arrow_pagination: "assets/img/icon/right_arrow_pagination.svg",
  elipse_1: "/assets/img/elipse_1.png",
  elipse_2: "/assets/img/elipse_2.png",
  elipse_3: "/assets/img/elipse_3.png",
  elipse_4: "/assets/img/elipse_4.png",
  elipse_5: "/assets/img/elipse_5.png",
  left_icon: "/assets/img/icon/left_icon.svg"
};
